<?php

namespace Container7PqHvYz;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_YUR7OhHService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.YUR7OhH' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.YUR7OhH'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'entree' => ['privates', '.errored..service_locator.YUR7OhH.App\\Entity\\Entree', NULL, 'Cannot autowire service ".service_locator.YUR7OhH": it references class "App\\Entity\\Entree" but no such service exists.'],
            'entreeRepository' => ['privates', 'App\\Repository\\EntreeRepository', 'getEntreeRepositoryService', true],
        ], [
            'entree' => 'App\\Entity\\Entree',
            'entreeRepository' => 'App\\Repository\\EntreeRepository',
        ]);
    }
}
