<?php

namespace Container7PqHvYz;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_KpOKYNRService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.kpOKYNR' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.kpOKYNR'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'entree' => ['privates', '.errored..service_locator.kpOKYNR.App\\Entity\\Entree', NULL, 'Cannot autowire service ".service_locator.kpOKYNR": it references class "App\\Entity\\Entree" but no such service exists.'],
        ], [
            'entree' => 'App\\Entity\\Entree',
        ]);
    }
}
