<?php

namespace Container7PqHvYz;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_C05l4dyService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.c05l4dy' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.c05l4dy'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'sortie' => ['privates', '.errored..service_locator.c05l4dy.App\\Entity\\Sortie', NULL, 'Cannot autowire service ".service_locator.c05l4dy": it references class "App\\Entity\\Sortie" but no such service exists.'],
            'sortieRepository' => ['privates', 'App\\Repository\\SortieRepository', 'getSortieRepositoryService', true],
        ], [
            'sortie' => 'App\\Entity\\Sortie',
            'sortieRepository' => 'App\\Repository\\SortieRepository',
        ]);
    }
}
