<?php

namespace Container7PqHvYz;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSortieService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.bZS4fRu.App\Entity\Sortie' shared service.
     *
     * @return \App\Entity\Sortie
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.bZS4fRu": it references class "App\\Entity\\Sortie" but no such service exists.');
    }
}
